### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by TAiS46** [fphilipe/premailer-rails#207] opened 2017-11-18 09:46 UTC
After update to 1.10.0 we got the following error

`TypeError: no implicit conversion of nil into String`

We have a css and include in the email template with this `<%= render 'mail_header' %>`

Email header contains

```
css:
  body {
    margin: 0;
    padding: 0;
  }

**Comment by fphilipe** [comment] 2017-11-19 10:59
Could you provide more info?

- Did you upgrade premailer as well?
- Which premailer-rails version were you using before?
- Can you provide a backtrace?

Thanks.

**Comment by olliebennett** [comment] 2017-11-20 11:57
I've also observed this; could only reproduce in production (on Heroku). Backtrace below.

We use the `mjml-rails` gem; not sure if that could interfere here.

Here's the `Gemfile.lock` diff which **led to** the bug, (good then bad) - apologies, there are too many changes here to be very useful; I'll bisect if/when I get a chance, but wanted to include all associated updates to avoid missing something apparently unrelated:

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 8fbbc5f44..4076d6e5d 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -47,9 +47,9 @@ GEM
       public_suffix (>= 2.0.2, < 4.0)
     arel (7.1.4)
     ast (2.3.0)
-    auto_strip_attributes (2.1.0)
+    auto_strip_attributes (2.2.0)
       activerecord (>= 3.0)
-    autoprefixer-rails (7.1.5)
+    autoprefixer-rails (7.1.6)
       execjs
     bcrypt (3.1.11)
     benchmark-ips (2.7.2)
@@ -58,7 +58,7 @@ GEM
       erubi (>= 1.0.0)
       rack (>= 0.9.0)
     bindex (0.5.0)
-    binding_of_caller (0.7.2)
+    binding_of_caller (0.7.3)
       debug_inspector (>= 0.0.1)
     bootstrap-kaminari-views (0.0.5)
       kaminari (>= 0.13)
@@ -66,7 +66,7 @@ GEM
     bootstrap-sass (3.3.7)
       autoprefixer-rails (>= 5.2.1)
       sass (>= 3.3.4)
-    bootstrap-slider-rails (9.2.0)
+    bootstrap-slider-rails (9.8.0)
       railties (>= 3.2, < 6.0)
     bootstrap-validator-rails (0.5.2)
       jquery-rails (>= 3.0)
@@ -82,7 +82,7 @@ GEM
       thor (~> 0.18)
     byebug (9.1.0)
     callsite (0.0.11)
-    capybara (2.15.4)
+    capybara (2.16.0)
       addressable
       mini_mime (>= 0.1.3)
       nokogiri (>= 1.3.3)
@@ -97,12 +97,12 @@ GEM
     consistency_fail (0.3.5)
     crack (0.4.3)
       safe_yaml (~> 1.0.0)
-    crass (1.0.2)
-    css_parser (1.5.0)
+    crass (1.0.3)
+    css_parser (1.6.0)
       addressable
     d3-rails (3.5.17)
       railties (>= 3.1)
-    daemons (1.2.4)
+    daemons (1.2.5)
     debug_inspector (0.0.3)
     derailed (0.1.0)
       derailed_benchmarks
@@ -130,10 +130,10 @@ GEM
     equalizer (0.0.11)
     erubi (1.7.0)
     erubis (2.7.0)
-    et-orbi (1.0.4)
+    et-orbi (1.0.8)
       tzinfo
     eventmachine (1.2.5)
-    excon (0.58.0)
+    excon (0.59.0)
     execjs (2.7.0)
     factory_bot (4.8.2)
       activesupport (>= 3.0.0)
@@ -142,7 +142,7 @@ GEM
       railties (>= 3.0.0)
     fakeredis (0.6.0)
       redis (~> 3.2)
-    faraday (0.11.0)
+    faraday (0.12.2)
       multipart-post (>= 1.2, < 3)
     ffi (1.9.18)
     figaro (1.1.1)
@@ -151,7 +151,7 @@ GEM
       rails (>= 4.0.0)
     fix-db-schema-conflicts (3.0.2)
       rubocop (>= 0.38.0)
-    fog-aws (1.4.0)
+    fog-aws (1.4.1)
       fog-core (~> 1.38)
       fog-json (~> 1.0)
       fog-xml (~> 0.1)
@@ -173,11 +173,10 @@ GEM
       rspec-core (~> 3.0)
       ruby-progressbar (~> 1.4)
     get_process_mem (0.2.1)
-    globalid (0.4.0)
+    globalid (0.4.1)
       activesupport (>= 4.2.0)
-    gon (6.1.0)
+    gon (6.2.0)
       actionpack (>= 3.0)
-      json
       multi_json
       request_store (>= 1.0)
     google_currency (3.4.0)
@@ -204,29 +203,29 @@ GEM
       guard (~> 2.0)
       rubocop (~> 0.20)
     hashdiff (0.3.7)
-    hashid-rails (1.1.0)
+    hashid-rails (1.1.1)
       activerecord (>= 4.0)
       hashids (~> 1.0)
     hashids (1.0.4)
-    hashie (3.5.5)
-    heapy (0.1.2)
+    hashie (3.5.6)
+    heapy (0.1.3)
     heroku-deflater (0.6.3)
       rack (>= 1.4.5)
     htmlentities (4.3.4)
-    http (2.2.2)
+    http (3.0.0)
       addressable (~> 2.3)
       http-cookie (~> 1.0)
-      http-form_data (~> 1.0.1)
+      http-form_data (>= 2.0.0.pre.pre2, < 3)
       http_parser.rb (~> 0.6.0)
     http-cookie (1.0.3)
       domain_name (~> 0.5)
-    http-form_data (1.0.3)
+    http-form_data (2.0.0)
     http_parser.rb (0.6.0)
     i18n (0.9.1)
       concurrent-ruby (~> 1.0)
     ideal_postcodes (2.0.0)
       rest-client (>= 1.8, < 3.0)
-    intercom (3.5.17)
+    intercom (3.5.22)
       json (>= 1.8)
     intercom-rails (0.3.5)
       activesupport (> 3.0)
@@ -238,18 +237,18 @@ GEM
     json (2.1.0)
     jsonapi-renderer (0.1.3)
     jwt (1.5.6)
-    kaminari (1.0.1)
+    kaminari (1.1.1)
       activesupport (>= 4.1.0)
-      kaminari-actionview (= 1.0.1)
-      kaminari-activerecord (= 1.0.1)
-      kaminari-core (= 1.0.1)
-    kaminari-actionview (1.0.1)
+      kaminari-actionview (= 1.1.1)
+      kaminari-activerecord (= 1.1.1)
+      kaminari-core (= 1.1.1)
+    kaminari-actionview (1.1.1)
       actionview
-      kaminari-core (= 1.0.1)
-    kaminari-activerecord (1.0.1)
+      kaminari-core (= 1.1.1)
+    kaminari-activerecord (1.1.1)
       activerecord
-      kaminari-core (= 1.0.1)
-    kaminari-core (1.0.1)
+      kaminari-core (= 1.1.1)
+    kaminari-core (1.1.1)
     kgio (2.11.0)
     koala (3.0.0)
       addressable
@@ -259,6 +258,7 @@ GEM
       addressable (~> 2.3)
     ledermann-rails-settings (2.4.2)
       activerecord (>= 3.1)
+    libxml-ruby (3.0.0)
     listen (3.1.5)
       rb-fsevent (~> 0.9, >= 0.9.4)
       rb-inotify (~> 0.9, >= 0.9.7)
@@ -271,8 +271,8 @@ GEM
       crass (~> 1.0.2)
       nokogiri (>= 1.5.9)
     lumberjack (1.0.12)
-    mail (2.6.6)
-      mime-types (>= 1.16, < 4)
+    mail (2.7.0)
+      mini_mime (>= 0.1.1)
     mangopay (3.0.29)
       multi_json (>= 1.7.7)
     memoizable (0.4.2)
@@ -286,7 +286,7 @@ GEM
       rails (>= 3.0.0)
     method_source (0.9.0)
     mime-types (2.99.3)
-    mini_mime (0.1.4)
+    mini_mime (1.0.0)
     mini_portile2 (2.3.0)
     minitest (5.10.3)
     minitest-capybara (0.8.2)
@@ -301,7 +301,7 @@ GEM
     minitest-rails (3.0.0)
       minitest (~> 5.8)
       railties (~> 5.0)
-    mjml-rails (2.4.2)
+    mjml-rails (2.4.3)
     monetize (1.4.0)
       money (~> 6.7)
     money (6.10.0)
@@ -312,16 +312,16 @@ GEM
       money (~> 6.7)
       railties (>= 3.0)
     mono_logger (1.1.0)
-    multi_json (1.12.1)
+    multi_json (1.12.2)
     multi_xml (0.6.0)
     multipart-post (2.0.0)
-    mustermann (1.0.0)
+    mustermann (1.0.1)
     naught (1.1.0)
     nenv (0.3.0)
     nestive (0.6.0)
       rails (>= 3.0.0)
     netrc (0.11.0)
-    newrelic_rpm (4.3.0.335)
+    newrelic_rpm (4.6.0.338)
     nio4r (2.1.0)
     nokogiri (1.8.1)
       mini_portile2 (~> 2.3.0)
@@ -334,8 +334,8 @@ GEM
       multi_json (~> 1.3)
       multi_xml (~> 0.5)
       rack (>= 1.2, < 3)
-    oj (3.1.4)
-    omniauth (1.6.1)
+    oj (3.3.9)
+    omniauth (1.7.1)
       hashie (>= 3.4.6, < 3.6.0)
       rack (>= 1.6.2, < 3)
     omniauth-facebook (4.0.0)
@@ -351,20 +351,20 @@ GEM
     parser (2.4.0.2)
       ast (~> 2.3)
     pg (0.21.0)
-    phonelib (0.6.13)
+    phonelib (0.6.16)
     poltergeist (1.16.0)
       capybara (~> 2.1)
       cliver (~> 0.3.1)
       websocket-driver (>= 0.2.0)
     powerpack (0.1.1)
-    premailer (1.10.4)
+    premailer (1.11.1)
       addressable
-      css_parser (>= 1.4.10)
+      css_parser (>= 1.6.0)
       htmlentities (>= 4.0.0)
-    premailer-rails (1.9.7)
+    premailer-rails (1.10.0)
       actionmailer (>= 3, < 6)
       premailer (~> 1.7, >= 1.7.9)
-    pry (0.11.2)
+    pry (0.11.3)
       coderay (~> 1.1.0)
       method_source (~> 0.9.0)
     pry-byebug (3.5.0)
@@ -372,7 +372,7 @@ GEM
       pry (~> 0.10)
     pry-rails (0.3.6)
       pry (>= 0.10.4)
-    public_suffix (3.0.0)
+    public_suffix (3.0.1)
     rabl (0.13.1)
       activesupport (>= 2.3.14)
     rack (2.0.3)
@@ -420,9 +420,9 @@ GEM
       thor (>= 0.18.1, < 2.0)
     rainbow (2.2.2)
       rake
-    raindrops (0.18.0)
+    raindrops (0.19.0)
     rake (12.3.0)
-    rb-fsevent (0.9.8)
+    rb-fsevent (0.10.2)
     rb-inotify (0.9.10)
       ffi (>= 0.5.0, < 2)
     redis (3.3.3)
@@ -489,7 +489,7 @@ GEM
     sass-listen (4.0.0)
       rb-fsevent (~> 0.9, >= 0.9.4)
       rb-inotify (~> 0.9, >= 0.9.7)
-    sass-rails (5.0.6)
+    sass-rails (5.0.7)
       railties (>= 4.0.0, < 6)
       sass (~> 3.1)
       sprockets (>= 2.8, < 4.0)
@@ -534,20 +534,21 @@ GEM
     thor (0.20.0)
     thread_safe (0.3.6)
     tilt (2.0.8)
-    twilio-ruby (4.13.0)
-      builder (>= 2.1.2)
-      jwt (~> 1.0)
-      multi_json (>= 1.3.0)
-    twitter (6.1.0)
-      addressable (~> 2.5)
+    twilio-ruby (5.4.5)
+      faraday (~> 0.9)
+      jwt (~> 1.5)
+      libxml-ruby (>= 2.0, < 4.0)
+    twitter (6.2.0)
+      addressable (~> 2.3)
       buftok (~> 0.2.0)
-      equalizer (= 0.0.11)
-      faraday (~> 0.11.0)
-      http (~> 2.1)
+      equalizer (~> 0.0.11)
+      http (~> 3.0)
+      http-form_data (~> 2.0)
       http_parser.rb (~> 0.6.0)
-      memoizable (~> 0.4.2)
-      naught (~> 1.1)
-      simple_oauth (~> 0.3.1)
+      memoizable (~> 0.4.0)
+      multipart-post (~> 2.0)
+      naught (~> 1.0)
+      simple_oauth (~> 0.3.0)
     tzinfo (1.2.4)
       thread_safe (~> 0.1)
     uglifier (3.2.0)
@@ -556,7 +557,7 @@ GEM
       unf_ext
     unf_ext (0.0.7.4)
     unicode-display_width (1.3.0)
-    unicorn (5.3.0)
+    unicorn (5.3.1)
       kgio (~> 2.6)
       raindrops (~> 0.7)
     uniform_notifier (1.10.0)
@@ -575,7 +576,7 @@ GEM
       hashdiff
     websocket-driver (0.6.5)
       websocket-extensions (>= 0.1.0)
-    websocket-extensions (0.1.2)
+    websocket-extensions (0.1.3)
     xpath (2.1.0)
       nokogiri (~> 1.3)
     zeroclipboard-rails (0.1.2)
```
Backtrace:

```
Rendered layouts/emails/_social_footer.mjml (0.0ms)
Rendered payment_mailer/request_payment.mjml.erb within layouts/emails/mjml_default (1.7ms)
TypeError: no implicit conversion of nil into String
	from /app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:164:in `join'
	from /app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:164:in `block in find_sources'
	from /app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:163:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:163:in `find_sources'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11:in `first'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11:in `load'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:47:in `block in load_css'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:46:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:46:in `load_css'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:38:in `load_css_with_cache'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:18:in `css_for_url'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:13:in `block in css_for_doc'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:13:in `map'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:13:in `css_for_doc'
	from /app/vendor/bundle/ruby/2.4.0/gems/premailer-rails-1.10.0/lib/premailer/rails/customized_premailer.rb:14:in `initialize'
... 7 levels...
	from /app/vendor/bundle/ruby/2.4.0/gems/mail-2.7.0/lib/mail/mail.rb:235:in `block in inform_interceptors'
	from /app/vendor/bundle/ruby/2.4.0/gems/mail-2.7.0/lib/mail/mail.rb:234:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/mail-2.7.0/lib/mail/mail.rb:234:in `inform_interceptors'
	from /app/vendor/bundle/ruby/2.4.0/gems/mail-2.7.0/lib/mail/message.rb:248:in `inform_interceptors'
	from /app/vendor/bundle/ruby/2.4.0/gems/mail-2.7.0/lib/mail/message.rb:258:in `deliver'
	from /app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.0.6/lib/action_mailer/message_delivery.rb:96:in `block in deliver_now'
	from /app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.0.6/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
	from /app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.0.6/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
	from (irb):4
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from /app/bin/rails:15:in `require'
	from /app/bin/rails:15:in `<main>'
```

**Comment by joshterry55** [comment] 2017-11-20 21:04
I too am having this issue since upgrading to 1.10.0
here is my backtrace 
Exception
----------------
no implicit conversion of nil into String

Backtrace
----------------
```/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:164:in `join'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:164:in `block in find_sources'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:163:in `each'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:163:in `find_sources'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11:in `each'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11:in `first'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_loaders/asset_pipeline_loader.rb:11:in `load'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:47:in `block in load_css'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:46:in `each'
/opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/premailer-rails-1.10.0/lib/premailer/rails/css_helper.rb:46:in `load_css'```

**Comment by ragesoss** [comment] 2017-11-22 22:12
Same!

**Comment by ragesoss** [comment] 2017-11-22 22:36
Rolling back only premailer-rails, while keeping the latest version of premailer (1.11.1) fixed it for me.

**Comment by epicatization** [comment] 2017-11-24 10:21
I can confirm, that latest version `premailer-rails (1.10.0)` was causing 
`TypeError: no implicit conversion of nil into String`  error.
As temp solution, as olliebennett mentioned - lock gem to older version.
`gem 'premailer-rails', '1.9.7'`

**Comment by olliebennett** [comment] 2017-11-24 11:04
If anyone is able to bisect the [changes](https://github.com/fphilipe/premailer-rails/compare/v1.9.7...v1.10.0) between `1.9.7` and `1.10.0`, to identify the exact commit which introduced the problem, I suspect it would help with preparing a fix.

**Comment by chesles** [comment] 2017-11-26 01:28
It looks like this started happening after #201 was merged; e79e1d8 works as expected and the merge commit (b540dbf5a82513b0e39f086a9712698f3c14c702) is the first where I see the error. Hope that's helpful!

**Comment by fphilipe** [comment] 2017-11-26 09:26
Thanks everyone for reporting. I'll have a closer look.

@kirs, @rafaelfranca, any idea what might be causing this? It seems related to the introduction of the the asset manifest in #201.

**Comment by rafaelfranca** [comment] 2017-11-27 03:00
That assets is not in the precompile list so it can't be found in the manifest. This exception is fixed on the 3.x branch of sprockets but even with the sprockets release people will need to add the assets to the precompile list

**Comment by fphilipe** [comment] 2017-11-27 06:20
@TAiS46, @joshterry55, @ragesoss, @epicatization, @olliebennett, @chesles, does adding the CSS file to the [sprockets manifest](http://guides.rubyonrails.org/asset_pipeline.html#manifest-files-and-directives) fix the problem, as @rafaelfranca suggested?

**Comment by chesles** [comment] 2017-11-27 13:50
In my case the file causing this appears to be a 3rd party font stylesheet link, which if I understand correctly can't be included in the manifest using `=require` directives:

```erb
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700' %>
```

Using a local copy of the file and referencing it using `=require` in my email.css file does fix the problem for me, though. Thanks for your help!

**Comment by kirs** [comment] 2017-11-29 12:00
Sorry about the issue. We've been rescuing similar exceptions from Sprockets, but not `TypeError`.

https://github.com/fphilipe/premailer-rails/pull/209 should fix the bug.

**Closed** 2017-11-29 12:19 UTC

**Comment by fphilipe** [comment] 2017-11-29 12:21
Version 1.10.1 was released. Thanks everyone!
