### ISSUE TITLE
Nokogiri doesn't have remove method

### ISSUE THREAD

**Issue by volkanunsal** [fphilipe/premailer-rails#149] opened 2016-01-25 22:00 UTC
I'm getting this error from my email template:

```
undefined method `remove' for #<Hpricot::Elem:0x007fe99a8bec60>
```

It comes from [this line](https://github.com/fphilipe/premailer-rails/blob/17c1fb3af30e3c410bf92f20b386eb6b46e337b3/lib/premailer/rails/css_helper.rb#L30). When I switch to using nokogiri, the error goes away. It seems like this line was added for nokogiri and wasn't checked against Hpricot. 

Can anyone confirm this?

**Comment by fphilipe** [comment] 2016-01-27 13:00
Good catch. I'm thinking of no longer supporting hpricot since it is declared dead. In any case, it still is advertised as supported and thus this is a legit bug. Just looked around, this seems to be the solution:

```ruby
link.parent.children.delete(link)
```

I'd be happy to accept a PR :wink:

**Comment by ericdfields** [comment] 2016-01-29 14:47
I'm still getting that Hpricot error even though I've specified Premailer-rails to use nokogiri in configs:

```
#config/initializers/premailer_rails.rb
Premailer::Rails.config.merge!(adapter: :nokogiri

#rails c
Premailer::Rails.config
=> {:input_encoding=>"UTF-8", :generate_text_part=>true, :adapter=>:nokogiri}
```

A separate gem uses Hpricot, so it's in my Gemfile.lock.

**Comment by fphilipe** [comment] 2016-01-29 15:23
I think that's just how Premailer works. Doesn't it say in the README (this gem) that Hpricot is used when both are loaded?

**Comment by ericdfields** [comment] 2016-01-29 15:36
Yeah, so Premailer is to blame?

**Comment by fphilipe** [comment] 2016-01-30 14:33
Yep. Actually I just checked an there is an `:adapter` config. Try setting that to `:nokogiri`.

**Comment by ericdfields** [comment] 2016-01-30 23:15
Didn’t work. I actually forked the gem that was using hpricot and adapted it to nokogiri… No hpricot in Gemfile.lock and now I’m all good…

Thanks for your help.

**Comment by kaluznyo** [comment] 2016-02-26 14:39
Any news on this ?

**Comment by ericdfields** [comment] 2016-02-26 15:13
@kaluznyo the problem is with premailer itself. The `:adapter` flag will work so long as you don't have hpricot in your Gemfile.lock. But if some other gem pulls in hpricot, it uses that no matter what.

@fphilipe feel free to close this issue since it's a premailer problem.

**Closed** 2016-04-10 02:11 UTC

**Comment by caJaeger** [comment] 2016-05-10 16:53
@ericdfields Shouldn't that have been "Feel free to fix this since it's a premailer problem"? Why woud the issue be closed with no solution?

**Comment by ericdfields** [comment] 2016-05-10 17:32
@caJaeger https://github.com/premailer/premailer/ is where the fix needs to happen. Out of scope for this gem.

**Comment by caJaeger** [comment] 2016-05-10 19:54
@ericdfields Ah, I did not realize there was a different gem!
